# -*- coding: utf-8 -*-
"""20QuestionsProject.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WXdArMUwJ8D6VVWqZGpeXs3gog0bXrSw
"""

# Cell 1
import json
import pandas as pd
import numpy as np
from pathlib import Path
import random
from collections import defaultdict

# Display settings
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', 100)

print("Libraries imported successfully!")

# Cell 2
# Load all possible nouns
with open('noun_universe.txt', 'r') as f:
    nouns = [line.strip() for line in f if line.strip()]

print(f"Total number of nouns: {len(nouns)}")
print(f"\nFirst 20 nouns:")
for i, noun in enumerate(nouns[:20], 1):
    print(f"{i}. {noun}")

print(f"\nLast 10 nouns:")
for i, noun in enumerate(nouns[-10:], len(nouns)-9):
    print(f"{i}. {noun}")

# Cell 3
# Load Property Universe File
with open('property_universe.txt', 'r') as f:
    properties = [line.strip() for line in f if line.strip()]

print(f"Total number of properties: {len(properties)}")
print(f"\nAll properties:")
for i, prop in enumerate(properties, 1):
    print(f"{i}. {prop}")

# Cell 4
# Load the combined student data (all_per_student.json)
with open('all_per_student.json', 'r') as f:
    student_data = json.load(f)

print("JSON Structure:")
print(f"Type: {type(student_data)}")

if isinstance(student_data, dict):
    print(f"Keys: {list(student_data.keys())[:10]}")  # Show first 10 keys

    # Show sample entry
    sample_key = list(student_data.keys())[0]
    print(f"\nSample entry for '{sample_key}':")
    print(json.dumps(student_data[sample_key], indent=2)[:500])  # First 500 chars
elif isinstance(student_data, list):
    print(f"Number of entries: {len(student_data)}")
    print(f"\nFirst entry:")
    print(json.dumps(student_data[0], indent=2)[:500])

# Cell 5
# Create a mapping to see which nouns have which properties already
property_coverage = defaultdict(int)
nouns_with_data = set()

if isinstance(student_data, dict):
    for noun, data in student_data.items():
        nouns_with_data.add(noun)
        if isinstance(data, dict) and 'properties' in data:
            for prop in data['properties']:
                property_coverage[prop] += 1

print(f"Nouns with existing data: {len(nouns_with_data)}")
print(f"Nouns without data: {len(set(nouns) - nouns_with_data)}")

print(f"\nTop 20 most common properties in existing data:")
sorted_props = sorted(property_coverage.items(), key=lambda x: x[1], reverse=True)
for prop, count in sorted_props[:20]:
    print(f"{prop}: {count} nouns")

# Cell 6
# Select the most useful properties for 20 questions

core_properties = [
    # Basic categorization
    'is_living', 'is_animal', 'is_plant', 'is_object', 'is_abstract',
    'is_natural', 'is_artificial',

    # Size and physical properties (1-10 scale)
    'size_scale_1_10',
    'weight_scale_1_10',
    'speed_scale_1_10',

    # Danger and safety
    'danger_to_humans_1_10',
    'fragility_scale_1_10',

    # Other useful properties
    'is_edible',
    'rarity_1_10',
    'typical_indoor_use_1_10',
    'portability_1_10',
    'tech_complexity_1_10',

    # Boolean properties
    'can_fly',
    'lives_in_water',
    'is_predator',
    'requires_electricity',
    'is_food',
    'is_vehicle',
    'is_tool',
    'is_furniture',
    'is_edible'
]

print(f"Selected {len(core_properties)} core properties:")
for i, prop in enumerate(core_properties, 1):
    print(f"{i}. {prop}")

!pip install torch transformers

# Cell 7
import torch
from transformers import AutoModelForCausalLM, AutoTokenizer, pipeline

print("Loading Phi-3 model...")
print("This may take a few minutes on first run...\n")

# Load the Phi-3 model
model = AutoModelForCausalLM.from_pretrained(
    "microsoft/Phi-3-mini-4k-instruct",
    device_map="cuda",  # Use "cpu" if no GPU available
    torch_dtype="auto",
    trust_remote_code=False,
)

tokenizer = AutoTokenizer.from_pretrained("microsoft/Phi-3-mini-4k-instruct")

# Create pipeline for text generation
pipe = pipeline(
    "text-generation",
    model=model,
    tokenizer=tokenizer,
    return_full_text=False,
    max_new_tokens=10,  # We only need short answers
    do_sample=False,    # Deterministic output
)

print("✅ Model loaded successfully!")

# Test the model
test_prompt = "What is 2+2? Answer with just the number."
test_response = pipe(test_prompt)[0]['generated_text'].strip()
print(f"\nTest prompt: {test_prompt}")
print(f"Test response: {test_response}")

# Cell 7b
def query_phi3(prompt, max_tokens=10, temperature=0.1):
    """
    Query phi-3 model using the loaded pipeline

    Args:
        prompt: The question/prompt to send to the model
        max_tokens: Maximum tokens to generate (keep low for yes/no answers)
        temperature: Sampling temperature (0.1 for consistency)

    Returns:
        Generated text response or None if error
    """
    try:
        # Generate response
        response = pipe(
            prompt,
            max_new_tokens=max_tokens,
            temperature=temperature,
            do_sample=temperature > 0,
            pad_token_id=tokenizer.eos_token_id
        )

        # Extract the generated text
        if response and len(response) > 0:
            generated_text = response[0]['generated_text'].strip()
            return generated_text
        else:
            return None

    except Exception as e:
        print(f"Error querying model: {e}")
        return None

# Test the query function
print("Testing query function:")
test_queries = [
    "Is an elephant larger than a mouse? Answer only yes or no.",
    "On a scale of 1-10, how dangerous is a lion? Answer with only a number.",
    "Can a fish fly? Answer only yes or no."
]

for query in test_queries:
    response = query_phi3(query)
    print(f"\nQ: {query}")
    print(f"A: {response}")

# Cell 8
# DELETED!!! CODE

# Cell 9
def parse_llm_response(response, property_type):
    """
    Parse the LLM response into a usable value
    Enhanced to handle phi-3 response formats
    """
    if not response:
        return None

    response = response.lower().strip()

    if property_type == 'binary':
        # Remove common artifacts
        response = response.replace('.', '').replace(',', '').replace('!', '')

        # Direct yes/no detection
        if response == 'yes':
            return True
        elif response == 'no':
            return False

        # Check if yes appears without no
        if 'yes' in response and 'no' not in response:
            return True
        elif 'no' in response and 'yes' not in response:
            return False

        # Check first word
        words = response.split()
        if words:
            first_word = words[0]
            if first_word == 'yes':
                return True
            elif first_word == 'no':
                return False

        # Default to None if ambiguous
        return None

    elif property_type == 'scale':
        # Extract number from response
        import re

        # Look for numbers 1-10
        numbers = re.findall(r'\b([1-9]|10)\b', response)

        if numbers:
            try:
                value = int(numbers[0])
                if 1 <= value <= 10:
                    return value
            except ValueError:
                pass

        # Try to find single digit at start
        if response and response[0].isdigit():
            try:
                value = int(response[0])
                if 1 <= value <= 10:
                    return value
            except ValueError:
                pass

        return None

    return None

# Test parsing with phi-3 style responses
print("Testing enhanced response parsing:")
test_responses = [
    ("yes", "binary"),
    ("no", "binary"),
    ("Yes.", "binary"),
    ("No, it cannot.", "binary"),
    ("7", "scale"),
    ("8.", "scale"),
    ("The answer is 5", "scale"),
    ("I would say 6 out of 10", "scale"),
    ("10", "scale"),
]

for response, ptype in test_responses:
    parsed = parse_llm_response(response, ptype)
    print(f"Response: '{response}' ({ptype}) → Parsed: {parsed}")

# Cell 9b
def create_property_prompt_v2(noun, property_name):
    """
    Create a prompt optimized for Phi-3's response style
    Uses more direct, instruction-style prompts
    """

    # Prompts for binary (yes/no) properties
    binary_prompts = {
        'is_edible': f"Question: Is a {noun} safe to eat?\nAnswer with only 'yes' or 'no':",
        'is_animal': f"Question: Is a {noun} an animal?\nAnswer with only 'yes' or 'no':",
        'is_plant': f"Question: Is a {noun} a plant?\nAnswer with only 'yes' or 'no':",
        'is_object': f"Question: Is a {noun} a physical object (not living, not abstract)?\nAnswer with only 'yes' or 'no':",
        'is_abstract': f"Question: Is a {noun} an abstract concept?\nAnswer with only 'yes' or 'no':",
        'is_natural': f"Question: Is a {noun} found in nature (not man-made)?\nAnswer with only 'yes' or 'no':",
        'is_artificial': f"Question: Is a {noun} man-made or artificial?\nAnswer with only 'yes' or 'no':",
        'can_fly': f"Question: Can a {noun} fly?\nAnswer with only 'yes' or 'no':",
        'lives_in_water': f"Question: Does a {noun} primarily live in water?\nAnswer with only 'yes' or 'no':",
        'is_predator': f"Question: Is a {noun} a predator?\nAnswer with only 'yes' or 'no':",
        'requires_electricity': f"Question: Does a {noun} require electricity to function?\nAnswer with only 'yes' or 'no':",
        'is_living': f"Question: Is a {noun} a living organism?\nAnswer with only 'yes' or 'no':",
        'is_food': f"Question: Is a {noun} typically used as food?\nAnswer with only 'yes' or 'no':",
        'is_vehicle': f"Question: Is a {noun} a vehicle?\nAnswer with only 'yes' or 'no':",
        'is_tool': f"Question: Is a {noun} a tool?\nAnswer with only 'yes' or 'no':",
        'is_furniture': f"Question: Is a {noun} furniture?\nAnswer with only 'yes' or 'no':"
    }

    # Prompts for scale (1-10) properties
    scale_prompts = {
        'size_scale_1_10': f"Question: On a scale of 1-10, how large is a {noun}? (1=tiny, 5=human-sized, 10=huge)\nAnswer with only a number 1-10:",
        'weight_scale_1_10': f"Question: On a scale of 1-10, how heavy is a {noun}? (1=very light, 5=moderate, 10=very heavy)\nAnswer with only a number 1-10:",
        'speed_scale_1_10': f"Question: On a scale of 1-10, how fast is a {noun}? (1=very slow, 5=moderate, 10=very fast)\nAnswer with only a number 1-10:",
        'danger_to_humans_1_10': f"Question: On a scale of 1-10, how dangerous is a {noun} to humans? (1=safe, 5=moderate risk, 10=very dangerous)\nAnswer with only a number 1-10:",
        'fragility_scale_1_10': f"Question: On a scale of 1-10, how fragile is a {noun}? (1=very durable, 5=moderate, 10=very fragile)\nAnswer with only a number 1-10:",
        'rarity_1_10': f"Question: On a scale of 1-10, how rare is a {noun}? (1=very common, 5=moderate, 10=very rare)\nAnswer with only a number 1-10:",
        'typical_indoor_use_1_10': f"Question: On a scale of 1-10, how often is a {noun} found indoors? (1=always outdoor, 5=both, 10=always indoor)\nAnswer with only a number 1-10:",
        'portability_1_10': f"Question: On a scale of 1-10, how portable is a {noun}? (1=immovable, 5=moveable, 10=easily carried)\nAnswer with only a number 1-10:",
        'tech_complexity_1_10': f"Question: On a scale of 1-10, how technologically complex is a {noun}? (1=no tech, 5=moderate, 10=high tech)\nAnswer with only a number 1-10:",
        'edibleness': f"Question: On a scale of 1-10, how edible is a {noun}? (1=inedible, 5=technically edible, 10=commonly eaten)\nAnswer with only a number 1-10:"
    }

    # Return appropriate prompt
    if property_name in binary_prompts:
        return binary_prompts[property_name], 'binary'
    elif property_name in scale_prompts:
        return scale_prompts[property_name], 'scale'
    else:
        return None, None

# Test the improved prompts
print("Testing improved prompts:")
test_noun = "elephant"
test_properties = ["is_animal", "size_scale_1_10", "can_fly"]

for prop in test_properties:
    prompt, ptype = create_property_prompt_v2(test_noun, prop)
    print(f"\n{'='*60}")
    print(f"Property: {prop}")
    print(f"Prompt:\n{prompt}")

    response = query_phi3(prompt)
    parsed = parse_llm_response(response, ptype)

    print(f"\nRaw response: {response}")
    print(f"Parsed value: {parsed}")

# Cell 10
def generate_noun_properties(noun, properties_list, verbose=True):
    """
    Generate all property values for a single noun using phi-3
    """
    noun_data = {'noun': noun}

    if verbose:
        print(f"\n{'='*60}")
        print(f"Processing: {noun}")
        print('='*60)

    for prop in properties_list:
        # Use the improved prompt function (v2)
        prompt, ptype = create_property_prompt_v2(noun, prop)

        if prompt and ptype:
            if verbose:
                print(f"\n  Property: {prop} ({ptype})")

            # Query the model
            response = query_phi3(prompt, max_tokens=15)  # Slightly more tokens for scale responses

            if response:
                parsed_value = parse_llm_response(response, ptype)
                noun_data[prop] = parsed_value

                if verbose:
                    print(f"  Response: {response}")
                    print(f"  Parsed: {parsed_value}")
            else:
                noun_data[prop] = None
                if verbose:
                    print(f"  ❌ No response")

    return noun_data

# Test with 3 sample nouns
print("Testing knowledge base generation with phi-3...")
sample_nouns = ['elephant', 'bicycle', 'cloud']  # Use specific nouns for testing
print(f"Test nouns: {sample_nouns}\n")

test_knowledge_base = []
for noun in sample_nouns:
    noun_data = generate_noun_properties(noun, core_properties, verbose=True)
    test_knowledge_base.append(noun_data)
    print("\n" + "="*60 + "\n")

print(f"\n✅ Generated data for {len(test_knowledge_base)} nouns")

# Cell 11 - Viewing Test Results
# Convert to DataFrame for easy viewing
test_df = pd.DataFrame(test_knowledge_base)
print("Test Knowledge Base:")
print(test_df.to_string())

# Check for any None values
print(f"\n\nMissing values per property:")
for col in test_df.columns:
    if col != 'noun':
        none_count = test_df[col].isna().sum()
        print(f"{col}: {none_count}/{len(test_df)} missing")

# Cell 12
# WARNING: This will take a LONG time with 2000+ nouns

PROCESS_ALL = True  # Set to True when ready for full run and False (if only want to run 100 nouns)
BATCH_SIZE = 100 if not PROCESS_ALL else len(nouns)

print(f"{'='*60}")
print(f"KNOWLEDGE BASE GENERATION")
print(f"{'='*60}")
print(f"Total nouns available: {len(nouns)}")
print(f"Properties per noun: {len(core_properties)}")
print(f"Processing: {BATCH_SIZE} nouns")
print(f"Estimated time: ~{BATCH_SIZE * len(core_properties) * 2 / 3600:.1f} hours")
print(f"Progress saves every: 50 nouns")
print(f"{'='*60}\n")

proceed = input("Proceed with generation? (yes/no): ")

if proceed.lower() == 'yes':
    knowledge_base = []

    nouns_to_process = nouns[:BATCH_SIZE]

    for i, noun in enumerate(nouns_to_process, 1):
        print(f"\n[{i}/{len(nouns_to_process)}] Processing: {noun}")

        noun_data = generate_noun_properties(noun, core_properties, verbose=False)
        knowledge_base.append(noun_data)

        # Save progress every 50 nouns
        if i % 50 == 0:
            temp_df = pd.DataFrame(knowledge_base)
            temp_df.to_json(f'knowledge_base_progress_{i}.json',
                          orient='records', indent=2)
            print(f"  💾 Progress saved: {i} nouns completed")

    print(f"\n✅ COMPLETE! Generated data for {len(knowledge_base)} nouns")

    # Save final knowledge base
    final_df = pd.DataFrame(knowledge_base)
    final_df.to_json('knowledge_base_full.json',
                  orient='records', indent=2)
    print(f"💾 Saved to: knowledge_base_full.json")
else:
    print("Generation cancelled.")